### ISSUE TITLE
Fix Spectre Model Rodeo/Dropship Animations

### ISSUE THREAD

**Issue by dbyale** [EnderBoy9217/Grunt-Mode#2]
Either find a way to change model pre-animation without crashing, or get new animations entirely

**Comment by anticode-403** [comment]
I've scene a video where Spectres were using a unique rodeo animation on Titans without issues. In Grunt Mode, it seems to work fine until they reached the battery - then it crashes once the player tries to remove the battery.

Since batteries are almost useless to the player anyways, have we considered disabling battery rodeos? If I recall correctly, Northstar has a "enable legacy rodeo" option. What does this do to rodeoing?

**Comment by dbyale** [comment]
Playtesters need to test if legacy rodeo works with spectre models. Someone can write a quick PR to change the model.
